site_name: "Lounge"
repo_name: ca-love/lounge
repo_url: https://github.com/ca-love/lounge
remote_branch: gh-pages

theme:
  name: material
  language: "en"
  palette:
    primary: red
    accent: red
  font:
    text: Open Sans
    code: Roboto Mono
  features:
    - navigation.expand

extra:
  manifest: manifest.webmanifest

nav:
  - "Overview": index.md
  - "Usage":
      - "ObjectAdapter Support": object-adapter.md
      - "GuidedStep Support": wip.md
      - "Paging Support": wip.md
      - "MaterialDesign Support": wip.md
      - "Navigation Support": wip.md
  - "Changelog": changelog.md
  - "API Docs":
      - "lounge": api/lounge/lounge
      - "lounge-databinding": api/lounge-databinding/lounge-databinding
      - "lounge-paging": api/lounge-paging/lounge-paging
      - "lounge-material": api/lounge-material/lounge-material
      - "lounge-navigation": api/lounge-navigation/lounge-navigation

markdown_extensions:
  - admonition
  - smarty
  - codehilite:
      guess_lang: false
      linenums: True
  - footnotes
  - meta
  - toc:
      permalink: true
  - pymdownx.arithmatex
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.inlinehilite
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tabbed
  - pymdownx.tilde
  - tables

plugins:
  - search
  - minify:
      minify_html: true
